### ISSUE TITLE
What  IS GRIVE CONFIGURED (BASED ON FIRST RUN SYNC NOW): NO

### ISSUE THREAD

**Issue by julianoolenick** [zecarneiro/griveIndicator#1]
My grive is already configured and synchronized with command line but by the indicator nothing happens.

**Comment by zecarneiro** [comment]
go to ~/.config/griveIndicator/griveIndicator.conf and change FIRSTCONFIG=0 to FIRSTCONFIG=1

Warning: If you have configuration to grive auto-sync, so disabled. because the grive indicator not detect when grive sync.
